import 'package:flutter_test/flutter_test.dart';
import 'package:ironlink/features/contacts/phone_normalizer.dart';

/// Guards the one failure mode that reports nothing when it happens.
///
/// Contact discovery works only if the device and the server reduce a number
/// to the exact same string before hashing. If they diverge, the digests
/// differ, the contact never matches, and there is no error anywhere — the
/// feature just quietly finds fewer people than it should. These vectors are
/// duplicated in `tests/test_contact_discovery.py`; changing one side without
/// the other must fail here.
void main() {
  group('normalization agrees with the server', () {
    phoneNormalizationVectors.forEach((input, expected) {
      test('${input.isEmpty ? '(empty)' : input} -> ${expected ?? 'null'}', () {
        expect(PhoneNormalizer.normalize(input), expected);
      });
    });
  });

  group('the ambiguous cases', () {
    test('a number already carrying its country code is not prefixed again', () {
      // Reading this as local would produce +2020109... which matches nothing.
      expect(PhoneNormalizer.normalize('201099695779'), '+201099695779');
    });

    test('every common spelling of one number converges', () {
      const spellings = [
        '01099695779',
        '+201099695779',
        '00201099695779',
        '201099695779',
        '1099695779',
        '+20 (109) 969-5779',
      ];
      final results = spellings.map(PhoneNormalizer.normalize).toSet();
      expect(results, hasLength(1),
          reason: 'these must all reduce to the same number');
      expect(results.single, '+201099695779');
    });

    test('another country keeps its own code', () {
      expect(PhoneNormalizer.normalize('+966501234567'), '+966501234567');
    });
  });

  group('hashing', () {
    const salt = 'test_contact_salt_at_least_32_chars_long_xx';

    test('is stable across calls', () {
      final a = PhoneNormalizer.hash('+201099695779', salt);
      final b = PhoneNormalizer.hash('+201099695779', salt);
      expect(a, b);
    });

    test('produces a 64-character hex digest', () {
      final digest = PhoneNormalizer.hash('+201099695779', salt);
      expect(digest, hasLength(64));
      expect(RegExp(r'^[0-9a-f]{64}$').hasMatch(digest), isTrue);
    });

    test('changes with the salt', () {
      expect(
        PhoneNormalizer.hash('+201099695779', 'a' * 40),
        isNot(PhoneNormalizer.hash('+201099695779', 'b' * 40)),
      );
    });

    test('different numbers do not collide', () {
      expect(
        PhoneNormalizer.hash('+201099695779', salt),
        isNot(PhoneNormalizer.hash('+201099695778', salt)),
      );
    });

    test('produces the exact digest the server computes', () {
      // Generated by the server implementation, not by this one:
      //   python -c "import hashlib; print(hashlib.sha256(
      //     f'{salt}+201099695779'.encode()).hexdigest())"
      //
      // This is the assertion that actually proves the two sides agree.
      // Everything else here would still pass if both implementations were
      // wrong in the same way; this would not.
      const fromServer =
          'c21346255ca70b38f4ab4c39da223589026cb47e18089cce636286fc8a4f1cb5';
      expect(PhoneNormalizer.hash('+201099695779', salt), fromServer);
    });
  });

  group('address book realities', () {
    test('entries that are not numbers are dropped, not thrown', () {
      const junk = ['', '   ', 'not a phone', 'email@example.com', '+', '++'];
      for (final entry in junk) {
        expect(PhoneNormalizer.normalize(entry), isNull, reason: entry);
      }
    });

    test('hashAll skips junk and de-duplicates', () {
      const salt = 'test_contact_salt_at_least_32_chars_long_xx';
      final digests = PhoneNormalizer.hashAll(
        [
          '01099695779',
          '+201099695779', // same number, different spelling
          'not a phone',
          '',
          '01099695778', // a genuinely different number
        ],
        salt,
      );
      expect(digests, hasLength(2),
          reason: 'the two spellings collapse to one digest');
    });
  });
}
