"""The models must be able to build the schema they describe.

This catches a defect the whole suite missed for as long as it existed, and it
runs anywhere — no database required.

`app/models/moderation.py` declared a partial index with `Text("message_id IS
NOT NULL")`: the column *type*, where the SQL construct `text(...)` belongs. It
never raised, because nothing in this repository had ever built the schema from
the models. The index itself was created by a hand-written migration that used
the right one, so the constraint was live in the database and the model was
simply an unfaithful description of it.

That is the quiet kind of wrong. It surfaced the first time anything called
`create_all` — and before that it would have produced a wrong autogenerated
migration, which is a much worse way to find out.

A mock engine renders the DDL without executing it, so this needs no Postgres
and belongs in the default run rather than behind `TEST_DATABASE_URL`.
"""

from __future__ import annotations

import pytest
from sqlalchemy import create_mock_engine

import app.models  # noqa: F401 — registers every table on the metadata
from app.models.base import Base


def test_every_table_can_be_created() -> None:
    statements: list[str] = []

    def capture(sql, *_args, **_kwargs) -> None:
        statements.append(str(sql))

    engine = create_mock_engine("postgresql://", capture)
    Base.metadata.create_all(engine, checkfirst=False)

    assert statements, "no DDL was produced"


def test_the_metadata_is_not_empty() -> None:
    # A guard on the guard: if the model package stops registering tables, the
    # test above passes trivially and proves nothing.
    assert len(Base.metadata.tables) > 20


@pytest.mark.parametrize(
    "table",
    ["users", "messages", "user_sessions", "content_reports", "user_blocks"],
)
def test_the_tables_the_product_depends_on_are_registered(table: str) -> None:
    assert table in Base.metadata.tables
