"""initial schema

Creates the full IronLink schema. alembic/versions/ was empty before this — no
table had ever been created by a migration, and scripts/init_db.sql provisions
only extensions and roles. This revision is therefore the baseline for all
22 tables, not an incremental change.

Requires the pgcrypto extension for the gen_random_uuid() server default; it is
created by scripts/init_db.sql and re-asserted here so the migration is
self-sufficient on a database that never ran that script (managed Postgres,
Supabase, Neon).

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-08-07T09:13:19.072013+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_object_key', sa.String(length=500), nullable=True),
    sa.Column('group_type', sa.String(length=20), nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='200', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('only_admins_can_post', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_announcement_group', sa.Boolean(), server_default='false', nullable=False, comment='Announcement channel: only ADMIN+ can post; members read-only'),
    sa.Column('join_approval_required', sa.Boolean(), server_default='true', nullable=False, comment='Joining requires admin approval (formal-workplace default)'),
    sa.Column('only_admins_can_add_members', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('disappearing_messages_seconds', sa.Integer(), nullable=True, comment='Group-level default for self-destruct timer; NULL = disabled'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_group_type'), 'groups', ['group_type'], unique=False)
    op.create_index('ix_groups_type_archived', 'groups', ['group_type', 'is_archived'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True, comment='Organizational unit — admin filters and targeted broadcasts'),
    sa.Column('fcm_token', sa.String(length=512), nullable=True, comment='Firebase Cloud Messaging device token; refreshed by the app'),
    sa.Column('hashed_military_id', sa.Text(), nullable=False, comment='bcrypt hash of the military service number — never store plaintext'),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('device_fingerprint', sa.Text(), nullable=True, comment='SHA-256 of (user-agent + OS build + screen resolution); used for anomalous login detection'),
    sa.Column('token_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('role', sa.String(length=20), server_default='soldier', nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='Account hard-expiry (e.g. contract end date). NULL = no expiry.'),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('avatar_object_key', sa.String(length=500), nullable=True, comment='MinIO object key; resolve to pre-signed URL on read'),
    sa.Column('mfa_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index('ix_users_expiry_date', 'users', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index('ix_users_status_role', 'users', ['status', 'role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True, comment='NULL = system-generated event'),
    sa.Column('actor_role', sa.String(length=20), nullable=True, comment='Snapshot of actor role at action time (role may change later)'),
    sa.Column('impersonator_id', sa.UUID(), nullable=True, comment='Set when an admin acts on behalf of another user'),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment="E.g. 'user', 'message', 'group'"),
    sa.Column('resource_id', sa.String(length=36), nullable=True, comment='UUID string of the affected resource'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra context: geo, device, flags — keyed arbitrarily'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True, comment='Links the log entry to the UserSession that was active'),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_action', 'audit_logs', ['actor_id', 'action'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_failures', 'audit_logs', ['action', 'created_at'], unique=False, postgresql_where='success = false')
    op.create_index('ix_audit_ip', 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('broadcasts',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=True, comment='NULL = all users; else only this department'),
    sa.Column('priority', sa.String(length=20), server_default='urgent', nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='Optional auto-expiry; NULL = manual ack only'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_department'), 'broadcasts', ['department'], unique=False)
    op.create_table('channels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_category'), 'channels', ['category'], unique=False)
    op.create_index(op.f('ix_channels_channel_type'), 'channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=False)
    op.create_index(op.f('ix_channels_owner_id'), 'channels', ['owner_id'], unique=False)
    op.create_table('communities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_category'), 'communities', ['category'], unique=False)
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=False)
    op.create_index(op.f('ix_communities_owner_id'), 'communities', ['owner_id'], unique=False)
    op.create_table('creator_dashboards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=False),
    sa.Column('total_subscribers', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_dashboards_user_id'), 'creator_dashboards', ['user_id'], unique=True)
    op.create_table('group_join_requests',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True, comment='Optional note to the group admin'),
    sa.Column('decided_by_id', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_join_requests_status'), 'group_join_requests', ['status'], unique=False)
    op.create_index('ix_join_req_group_status', 'group_join_requests', ['group_id', 'status'], unique=False)
    op.create_index('ix_join_req_unique_pending', 'group_join_requests', ['group_id', 'user_id'], unique=True)
    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_muted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_message_id', sa.UUID(), nullable=True, comment='Used for unread-count computation without a full messages scan'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_group_members_unique', 'group_members', ['group_id', 'user_id'], unique=True)
    op.create_index('ix_group_members_user', 'group_members', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content_ciphertext', sa.Text(), nullable=True, comment='E2E encrypted blob; NULL for system messages'),
    sa.Column('media_object_key', sa.String(length=500), nullable=True),
    sa.Column('media_mime_type', sa.String(length=100), nullable=True),
    sa.Column('media_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('reply_to_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_self_destruct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('destruct_after_seconds', sa.Integer(), nullable=True, comment='Seconds after first read; NULL = no timer'),
    sa.Column('destruct_at', sa.DateTime(timezone=True), nullable=True, comment='Absolute UTC timestamp when message must be wiped'),
    sa.Column('is_destructed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp; message row retained for audit trail'),
    sa.Column('deleted_for_everyone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('edit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_destruct_at'), 'messages', ['destruct_at'], unique=False)
    op.create_index(op.f('ix_messages_group_id'), 'messages', ['group_id'], unique=False)
    op.create_index(op.f('ix_messages_recipient_id'), 'messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index('ix_msg_destruct', 'messages', ['destruct_at'], unique=False, postgresql_where='is_destructed = false AND destruct_at IS NOT NULL')
    op.create_index('ix_msg_dm_conv', 'messages', ['sender_id', 'recipient_id', 'created_at'], unique=False)
    op.create_index('ix_msg_group_conv', 'messages', ['group_id', 'created_at'], unique=False)
    op.create_index('ix_msg_status', 'messages', ['status'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False, comment='SHA-256 of the refresh token — never store plaintext'),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True, comment='mobile | tablet | desktop | unknown'),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('geo_country', sa.String(length=2), nullable=True),
    sa.Column('geo_city', sa.String(length=100), nullable=True),
    sa.Column('geo_lat', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('geo_lon', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Set by admin force-logout or user sign-out; NULL = active'),
    sa.Column('ws_connection_id', sa.String(length=64), nullable=True, comment='Redis WS session key for remote disconnect'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index('ix_sessions_expires', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_ip', 'user_sessions', ['ip_address'], unique=False)
    op.create_index('ix_sessions_user_revoked', 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('broadcast_acks',
    sa.Column('broadcast_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broadcast_ack_unique', 'broadcast_acks', ['broadcast_id', 'user_id'], unique=True)
    op.create_index('ix_broadcast_ack_user', 'broadcast_acks', ['user_id'], unique=False)
    op.create_table('channel_analytics',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('new_subscribers', sa.Integer(), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_posts', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_analytics_channel_id'), 'channel_analytics', ['channel_id'], unique=False)
    op.create_table('channel_posts',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_key', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_posts_channel_created', 'channel_posts', ['channel_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_channel_posts_channel_id'), 'channel_posts', ['channel_id'], unique=False)
    op.create_table('channel_subscriptions',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_subscriptions_channel_id'), 'channel_subscriptions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_subscriptions_user_id'), 'channel_subscriptions', ['user_id'], unique=False)
    op.create_index('uq_channel_subscription_channel_user', 'channel_subscriptions', ['channel_id', 'user_id'], unique=True)
    op.create_table('community_events',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_events_community_id'), 'community_events', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_events_start_time'), 'community_events', ['start_time'], unique=False)
    op.create_table('community_members',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_members_community_id'), 'community_members', ['community_id'], unique=False)
    op.create_index(op.f('ix_community_members_user_id'), 'community_members', ['user_id'], unique=False)
    op.create_index('uq_community_members_community_user', 'community_members', ['community_id', 'user_id'], unique=True)
    op.create_table('community_permissions',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('can_comment', sa.Boolean(), nullable=False),
    sa.Column('can_delete_own_posts', sa.Boolean(), nullable=False),
    sa.Column('can_delete_any_posts', sa.Boolean(), nullable=False),
    sa.Column('can_mute_members', sa.Boolean(), nullable=False),
    sa.Column('can_ban_members', sa.Boolean(), nullable=False),
    sa.Column('can_invite_members', sa.Boolean(), nullable=False),
    sa.Column('can_change_settings', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_permissions_community_id'), 'community_permissions', ['community_id'], unique=False)
    op.create_index('uq_community_permissions_community_role', 'community_permissions', ['community_id', 'role'], unique=True)
    op.create_table('community_resources',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_resources_community_id'), 'community_resources', ['community_id'], unique=False)
    op.create_table('payouts',
    sa.Column('creator_dashboard_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_dashboard_id'], ['creator_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_creator_dashboard_id'), 'payouts', ['creator_dashboard_id'], unique=False)
    op.create_index(op.f('ix_payouts_creator_id'), 'payouts', ['creator_id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('community_event_rsvps',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['community_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_event_rsvps_event_id'), 'community_event_rsvps', ['event_id'], unique=False)
    op.create_index('uq_community_event_rsvps_event_user', 'community_event_rsvps', ['event_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_community_event_rsvps_event_user', table_name='community_event_rsvps')
    op.drop_index(op.f('ix_community_event_rsvps_event_id'), table_name='community_event_rsvps')
    op.drop_table('community_event_rsvps')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_creator_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_creator_dashboard_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_community_resources_community_id'), table_name='community_resources')
    op.drop_table('community_resources')
    op.drop_index('uq_community_permissions_community_role', table_name='community_permissions')
    op.drop_index(op.f('ix_community_permissions_community_id'), table_name='community_permissions')
    op.drop_table('community_permissions')
    op.drop_index('uq_community_members_community_user', table_name='community_members')
    op.drop_index(op.f('ix_community_members_user_id'), table_name='community_members')
    op.drop_index(op.f('ix_community_members_community_id'), table_name='community_members')
    op.drop_table('community_members')
    op.drop_index(op.f('ix_community_events_start_time'), table_name='community_events')
    op.drop_index(op.f('ix_community_events_community_id'), table_name='community_events')
    op.drop_table('community_events')
    op.drop_index('uq_channel_subscription_channel_user', table_name='channel_subscriptions')
    op.drop_index(op.f('ix_channel_subscriptions_user_id'), table_name='channel_subscriptions')
    op.drop_index(op.f('ix_channel_subscriptions_channel_id'), table_name='channel_subscriptions')
    op.drop_table('channel_subscriptions')
    op.drop_index(op.f('ix_channel_posts_channel_id'), table_name='channel_posts')
    op.drop_index('ix_channel_posts_channel_created', table_name='channel_posts')
    op.drop_table('channel_posts')
    op.drop_index(op.f('ix_channel_analytics_channel_id'), table_name='channel_analytics')
    op.drop_table('channel_analytics')
    op.drop_index('ix_broadcast_ack_user', table_name='broadcast_acks')
    op.drop_index('ix_broadcast_ack_unique', table_name='broadcast_acks')
    op.drop_table('broadcast_acks')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index('ix_sessions_user_revoked', table_name='user_sessions')
    op.drop_index('ix_sessions_ip', table_name='user_sessions')
    op.drop_index('ix_sessions_expires', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_msg_status', table_name='messages')
    op.drop_index('ix_msg_group_conv', table_name='messages')
    op.drop_index('ix_msg_dm_conv', table_name='messages')
    op.drop_index('ix_msg_destruct', table_name='messages', postgresql_where='is_destructed = false AND destruct_at IS NOT NULL')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_group_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_destruct_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_group_members_user', table_name='group_members')
    op.drop_index('ix_group_members_unique', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('ix_join_req_unique_pending', table_name='group_join_requests')
    op.drop_index('ix_join_req_group_status', table_name='group_join_requests')
    op.drop_index(op.f('ix_group_join_requests_status'), table_name='group_join_requests')
    op.drop_table('group_join_requests')
    op.drop_index(op.f('ix_creator_dashboards_user_id'), table_name='creator_dashboards')
    op.drop_table('creator_dashboards')
    op.drop_index(op.f('ix_communities_owner_id'), table_name='communities')
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    op.drop_index(op.f('ix_communities_category'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_channels_owner_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_type'), table_name='channels')
    op.drop_index(op.f('ix_channels_category'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_broadcasts_department'), table_name='broadcasts')
    op.drop_table('broadcasts')
    op.drop_index('ix_audit_resource', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_ip', table_name='audit_logs')
    op.drop_index('ix_audit_failures', table_name='audit_logs', postgresql_where='success = false')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_actor_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status_role', table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index('ix_users_expiry_date', table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_index('ix_groups_type_archived', table_name='groups')
    op.drop_index(op.f('ix_groups_group_type'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
